# Generated by Django 5.2.4 on 2025-07-27 19:42

from django.db import migrations, models

import habits.validators


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="rewards",
            new_name="reward",
        ),
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveSmallIntegerField(
                validators=[habits.validators.ExecutionTimeValidator(120)],
                verbose_name="Время на выполнение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity_days",
            field=models.PositiveIntegerField(
                default=1,
                validators=[habits.validators.PeriodicityValidator(limit_value=7)],
                verbose_name="Периодичность",
            ),
        ),
    ]
